## Agenda

<b><br>
>What is Numpy and its Business Application.
><br>Numpy vs List
><br>Numpy Operations
><br>Broadcasting
><br>Numerical Data Analysis
><br>Python Webframeworks : Django   

## Numpy - Introduction

In [1]:
li = ['hello',23.0]

<html>
<b>What is NumPy?</b>
<br> NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.

It is the fundamental package for scientific computing with Python. 

<b><br>It contains various features including these important ones:</b>

>A powerful N-dimensional array object
><br>Sophisticated (broadcasting) functions
><br>Tools for integrating C/C++ and Fortran code
><br>Useful linear algebra,Linear equation  and random number capabilities

<html>
<h7>Scalar: A scalar is a real number
    <br>Vector : A vector is an object that has both a magnitude and a direction.</h7>
<br><a href="https://qph.fs.quoracdn.net/main-qimg-95b50a8a210d701e089a453b1f928932"/>Explanation</a>

In [48]:
import numpy as np

### Array Creation

#### One dimensional Array

In [49]:
ar = np.array( [ 1, 2, 3] )

In [50]:
ar

array([1, 2, 3])

In [51]:
ar.ndim

1

#### Multi-dimensional Array

In [52]:
# basic array characteristics 
# Creating array object 
ar = np.array( [[ 1, 2, 3],[2, 3, 4]] )

print("Array is of type: ", type(ar)) 
print("No. of dimensions: ", ar.ndim) 
print("Shape of array: ", ar.shape)
print("item size stored in a memory: ", ar.itemsize)
print("Size of array: ", ar.size) 
print("Array stores elements of type: ", ar.dtype) 


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
item size stored in a memory:  4
Size of array:  6
Array stores elements of type:  int32


In [53]:
a = np.array([1,2.3])
a.dtype
a

array([1. , 2.3])

<html>
    <b>NumPy Array v/s List</b>
<br>Why NumPy is used in Python?
<br>We use python NumPy array instead of a list because of the below three reasons:
<br>1)Less Memory
<br>2)Fast
<br>3)Convenient

In [8]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
!pip install <pkg name>

The syntax of the command is incorrect.


In [54]:
#Memory occupency
import numpy as np
 
import time
import sys
S= range(1000)
print(sys.getsizeof(5)*len(S))
 
D= np.arange(1000)
print(D.size*D.itemsize)

28000
4000


In [11]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [55]:
#Time taken for execution
import time
import sys
 
SIZE = 1000000
 
L1= range(SIZE)
L2= range(SIZE)
A1= np.arange(SIZE)
A2=np.arange(SIZE)
 
start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)
 
start=time.time()
result= A1+A2
print((time.time()-start)*1000)

308.02416801452637
81.00223541259766


#### Exploring basic Numpy Functions

In [13]:
np.random.random(5)

array([0.68029454, 0.2403532 , 0.32024917, 0.64162381, 0.7804705 ])

In [56]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float') 
print ("Array created using passed list:\n", a) 

b = np.array((1 , 3, 2)) 
print ("\nArray created using passed tuple:\n", b) 

c = np.zeros((3, 4)) 
print ("\nAn array initialized with all zeros:\n", c) 

e = np.random.random((2, 2)) 
print ("\nA random array:\n", e) 

f = np.arange(0, 30, 5) 
print ("\nA sequential array with steps of 5:\n", f) 

g = np.linspace(0, 5, 10) 
print ("\nA sequential array with 10 values between 0 and 5:\n", g) 



Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

A random array:
 [[0.70806004 0.58413504]
 [0.48563784 0.30053964]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

A sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [57]:
arr = np.array([[1, 2, 3, 4], [5, 2, 4, 2,6], [1, 2, 0, 1]]) 

C:\Users\1513353\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [58]:
# Reshaping 3X4 array to 2X2X3 array 
arr = np.array([[1, 2, 3, 4], [5, 2, 4, 2], [1, 2, 0, 1]]) 

newarr = arr.reshape(2, 2, 3) 

print ("\nOriginal array:\n", arr) 
print ("Reshaped array:\n", newarr) 

# Flatten array 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
flarr = arr.flatten() 
a = arr.ravel()
print("ravel",a)
print ("\nOriginal array:\n", arr) 
print ("Fattened array:\n", flarr) 



Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]
ravel [1 2 3 4 5 6]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


In [59]:
a2 = np.array([1,2,34])
a2[0:1]

array([1])

In [17]:
li = [0,1,2,3,4,5]
li[2:]

[2, 3, 4, 5]

In [60]:
# indexing in numpy 
import numpy as np 


arr = np.array([[-1, 2, 0, 4], 
[4, -0.5, 6, 0], 
[2.6, 0, 7, 8], 
[3, -7, 4, 2.0]]) 

print(arr[0][0])

temp = arr[:2, ::3] 
print ("Array with first 2 rows and alternatecolumns(0 and 2):\n", temp) 
 
cond = arr > 0 
temp = arr[cond] 
print ("\nElements greater than 0:\n", temp) 


-1.0
Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  4.]
 [ 4.  0.]]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


### Basic Operations

In [19]:
[1,2,3] +1

[1, 2, 3, 1, 1, 1]

In [61]:
# basic arthematic operations 
import numpy as np 

a = np.array([1, 2, 5, 3]) 

print ("Adding 1 to every element:", a+1) 
print ("Subtracting 3 from each element:", a-3) 
print ("Multiplying each element by 10:", a*10) 
print ("Squaring each element:", a**2) 

a *= 2
print ("Doubled each element of original array:", a) 

 
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]]) 

print ("\nOriginal array:\n", a) 
print ("Transpose of array:\n", a.transpose()) 
a.T

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


array([[1, 3, 9],
       [2, 4, 6],
       [3, 5, 0]])

* axis = 0 columnwise vectors
* axis = 1 rowwise vectors

In [21]:
# unary operators in numpy 
import numpy as np 
  
arr = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]]) 
  
print ("Largest element is:", arr.max()) 
print ("Row-wise maximum elements:", arr.max(axis = 1)) 
print ("Column-wise minimum elements:", arr.min(axis = 0)) 
print ("Sum of all array elements:", arr.sum(axis = 0)) 
print ("Cumulative sum along each row:\n", arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: [ 8 13 17]
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [22]:
# binary operators in Numpy 
a = np.array([[1, 2], [3, 4]]) 
b = np.array([[4, 3], [2, 1]]) 

print ("Array sum:\n", a + b) 
print ("Array multiplication:\n", a*b) 
print ("Matrix multiplication:\n", a.dot(b)) 
 

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [23]:
# unfunctions in numpy 
a = np.array([0, np.pi/2, np.pi]) 
print ("Sine values of array elements:", np.sin(a)) 

a = np.array([0, 1, 2, 3]) 
print ("Exponent of array elements:", np.exp(a)) 
print ("Square root of array elements:", np.sqrt(a)) 


Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


### sorting

In [62]:
# sorting in numpy 


a = np.array([[1, 4, 2], [3, 4, 6], [0, -1, 5]]) 

print ("Array elements in sorted order:\n", np.sort(a, axis = None)) 
print ("Row-wise sorted array:\n", np.sort(a, axis = 0)) 
print ("Column wise sort by applying merge-sort:\n", np.sort(a, axis = 0, kind = 'mergesort')) 


Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


### structured array 

In [63]:
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)] 

values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)] 

# Creating array 
arr = np.array(values, dtype = dtypes) 
print ("\nArray sorted by names:\n",np.sort(arr, order = 'name')) 
print ("Array sorted by grauation year and then cgpa:\n", np.sort(arr, order = ['grad_year', 'cgpa'])) 



Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by grauation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [26]:
x = np.array([('a', 0.8), ('b', 0.2)], dtype=[('label', 'a8'), ('prob', 'f8')])
x['label']

array([b'a', b'b'], dtype='|S8')

### Stacking & Splitting

<b>Stacking: Several arrays can be stacked together along different axes.</b>
    <br>np.vstack: To stack arrays along vertical axis.
    <br>np.hstack: To stack arrays along horizontal axis.
    <br>np.column_stack: To stack 1-D arrays as columns into 2-D arrays.
    <br>np.concatenate: To stack arrays along specified axis (axis is passed as argument).

In [64]:
a = np.array([[1, 2], [3, 4]]) 

b = np.array([[5, 6],[7, 8]]) 

print("Vertical stacking:\n", np.vstack((a, b))) 
print("\nHorizontal stacking:\n", np.hstack((a, b))) 

c = [5, 6] 
print("\nColumn stacking:\n", np.column_stack((a, c))) 
print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b),axis = 1)) 


Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


In [29]:
a = np.array([[1, 3, 5, 7, 9, 11], [2, 4, 6, 8, 10, 12]]) 
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2)) 
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(a, 2))


Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]

Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


### Broadcasting

<html>
<br>The term broadcasting describes how NumPy treats arrays 
with different shapes during arithmetic operations. 

Taken from the Numpy documentation - <br>
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

* they are equal, or
* one of them is 1    
    


In [30]:
a = np.array([[1,2,3,4],[2,3,4,5]])
a.shape

(2, 4)

##### Examples

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
## Match
A(4-D array): 7 x 1 x 6 x 1
B(3-D array):     3 x 1 x 5
Result      : 7 x 3 x 6 x 5


SyntaxError: invalid syntax (<ipython-input-32-99e6e0130a2c>, line 2)

In [33]:
## Miss Match
A: 4 x 3
B:     4

SyntaxError: invalid syntax (<ipython-input-33-3445aaaca999>, line 2)

In [65]:
### Match
import numpy as np 

a = np.array([1.0, 2.0, 3.0]) 


b = 2.0
print(a * b) 


c = [2.0, 2.0, 2.0] 
print(a * c)


[2. 4. 6.]
[2. 4. 6.]


In [66]:
## Miss match
a = np.array([[1, 2,2], [3, 4,3],[5,6,4],[6,8,5]])

In [67]:
a.shape

(4, 3)

In [68]:
b = np.array([1,2,3,4])

In [69]:
b.shape

(4,)

In [70]:
a*b

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

<b>Working with datetime:</b> 
    <br>Numpy has core array data types which natively support datetime functionality. 
    <br>The data type is called “datetime64”, so named because “datetime” is already taken
    by the datetime library included in Python.

In [40]:
# creating a date 
today = np.datetime64('2017-02-12') 
print("Date is:", today) 
print("Year is:", np.datetime64(today, 'Y'))
print("Year is:", np.datetime64(today, 'M'))
print("Year is:", np.datetime64(today, 'D'))

Date is: 2017-02-12
Year is: 2017
Year is: 2017-02
Year is: 2017-02-12


In [71]:
np.datetime64('2005') == np.datetime64('2005-01-01')

True

### Linear Algebra

<html>
Linear algebra in NumPy: 
    The Linear Algebra module of NumPy offers various methods to apply linear algebra on any numpy array.
    
>*You can explore:
><br>*rank, determinant, trace, etc. of an array.
><br>*matrix and vector products (dot, inner, outer,etc. product), matrix exponentiation
><br>*solve linear equations and much more!

In [72]:
A = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]]) 

print("Rank of A:", np.linalg.matrix_rank(A)) 

print("\nTrace of A:", np.trace(A)) 

print("\nDeterminant of A:", np.linalg.det(A)) 

print("\nInverse of A:\n", np.linalg.inv(A)) 

print("\nMatrix A raised to power 3:\n", np.linalg.matrix_power(A, 3))


Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


### Solving Linear Equations

<html>

>x + 2*y = 8
><br>3*x + 4*y = 18

In [73]:
# coefficients 
a = np.array([[1, 2], [3, 4]]) 
# constants 
b = np.array([8, 18]) 

print("Solution of linear equations:", np.linalg.solve(a, b))


Solution of linear equations: [2. 3.]


### Integration

In [44]:
from scipy import special
from scipy import integrate 
i = integrate.quad(lambda x:special.exp10(x),0,1 )
i

(3.9086503371292665, 4.3394735994897923e-14)

##### C++ extensions

In [45]:
import numpy as N
from numpyctypes import c_ndarray

ModuleNotFoundError: No module named 'numpyctypes'

##### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats
print(np.min(stats))
print(np.max(stats, axis=1))
print(np.sum(stats, axis=0))

#### Can we Save Numpy Array?

In [75]:
arr = np.array([1,2,3,4])
np.save('test',arr)

In [76]:
#load an array
np.load('test.npy')

array([1, 2, 3, 4])

In [ ]:
np.savetxt('hello.csv',arr,delimiter = ',')

######## saves file in file format #####

In [46]:
arr = open('hello.csv','r')
for i in arr:
    print(i)
arr.close()

FileNotFoundError: [Errno 2] No such file or directory: 'hello.csv'

### Reference Links

http://scipy.github.io/devdocs/tutorial/linalg.html

https://numpy.org/doc/1.18/reference/index.html